
# mlflow settings
mlflow:
  experiment_name: final_run

# General information for model training
general:
  batch_size: 8
  num_workers: 10
  epochs: 20
  device: cuda
  threshold: 0.5
# Dataset parameters
dataset:
  label_names: [aburazemi, higurashi, minminzemi, niiniizemi, tsukutsukuboushi]
  sr: 16000
  win_sec: 4
  stride_sec: 4
# Feature extraction
feature:
  feature: spectrogram # spectrogram, or melspectrogram
  highpass_cutoff: 600 # Use null for not setting
  lowpass_cutoff: null # Use null for not setting
  n_fft: 800
  n_mels: 256
# Hyperparameters of the model
model:
  model_name: efficientnet_b4
  n_layers: 1
  h_dims: 64
  batch_norm: True
  drop_out: 0.5
  learning_rate: 0.0005
  loss: mse # mse, bce

generation:
  length: 20 # in seconds
  n_train: 25000
  n_test: 5000
  cicada_ratio: 0.9 # Ratio of simulation with cicada songs
  train_dir: /home/okamoto/CicadaChorusDetection/step3_model_training/data/train
  test_dir: /home/okamoto/CicadaChorusDetection/step3_model_training/data/test
  
  cicadas:
    weights: # weights of each cicada species
      aburazemi: 1
      higurashi: 1
      minminzemi: 1
      niiniizemi: 1
      tsukutsukuboushi: 1
    popsize:
      min: 5 # minimum number of cicadas
      max: 5 # maximum number of cicadas
    distance:
      min: 60.0 # minimum distance between the mic and cicadas in meters.
      max: 120.0 # maximum distance between the mic and cicadas in meters.
    n_species:
      min: 1 # minimum number of cicada species
      max: 5 # maximum number of cicada species

  others:
    weights:
      birds: 1
      esc50: 1
      insects: 1
    popsize:
      min: 0
      max: 5
    distance:
      min: 10.0
      max: 120.0
    n_species:
      min: 1
      max: 3
  # Augumentation settings
  augs:
    pitch_shift:
      null # null for not using
      #min: -1
      #max: 1